// Module2_FrontendDev_Shivatharani/HandsOn6/src/components/CourseCard.jsx
import { useNavigate } from "react-router-dom";
import { useDispatch } from "react-redux";
import { enroll } from "../redux/enrollmentSlice";

function CourseCard({
    id,
    name,
    code,
    credits,
    grade
}) {

    const navigate = useNavigate();

    const dispatch = useDispatch();

    function handleEnroll() {

        dispatch(
            enroll({
                id,
                name,
                code,
                credits,
                grade
            })
        );

        navigate("/profile");

    }

    function viewDetails() {

        navigate(`/courses/${id}`);

    }

    return (

        <div className="course-card">

            <h3>{name}</h3>

            <p>

                <strong>Course Code :</strong> {code}

            </p>

            <p>

                <strong>Credits :</strong> {credits}

            </p>

            <p>

                <strong>Grade :</strong> {grade}

            </p>

            <button
                className="enroll-btn"
                onClick={handleEnroll}
            >
                Enroll
            </button>

            <button
                className="enroll-btn"
                style={{
                    marginTop: "10px",
                    background: "#43a047"
                }}
                onClick={viewDetails}
            >
                View Details
            </button>

        </div>

    );

}

export default CourseCard;

// Module2_FrontendDev_Shivatharani/HandsOn8/src/components/CourseCard.vue
<template>

<div class="card">

<h2>{{ name }}</h2>

<p><b>Code:</b> {{ code }}</p>

<p><b>Credits:</b> {{ credits }}</p>

<p><b>Grade:</b> {{ grade }}</p>

<RouterLink :to="'/courses/'+id">

<button>

View Details

</button>

</RouterLink>

<button @click="$emit('enroll')">

Enroll

</button>

</div>

</template>

<script setup>

defineProps({

id:Number,

name:String,

code:String,

credits:Number,

grade:String

});

</script>

<style scoped>

.card{

transition:.3s;

}

.card:hover{

transform:scale(1.03);

}

</style>
