// Module2_FrontendDev_Shivatharani/HandsOn6/src/components/Header.jsx
import { Link } from "react-router-dom";

import { useSelector }

from "react-redux";

function Header() {

    const enrolledCourses = useSelector(

        state =>

        state.enrollment.enrolledCourses

    );

    return (

        <header className="header">

            <div className="header-container">

                <div>

                    <h1>

                        🎓 Student Portal

                    </h1>

                    <p>

                        React Router + Redux Toolkit

                    </p>

                </div>

                <nav>

                    <ul>

                        <li>

                            <Link to="/">Home</Link>

                        </li>

                        <li>

                            <Link to="/courses">

                                Courses

                            </Link>

                        </li>

                        <li>

                            <Link to="/profile">

                                Profile

                            </Link>

                        </li>

                    </ul>

                </nav>

                <div className="enrolled">

                    Enrolled :

                    {enrolledCourses.length}

                </div>

            </div>

        </header>

    );

}

export default Header;

// Module2_FrontendDev_Shivatharani/HandsOn8/src/components/Header.vue
<template>
<nav>

<div>
<RouterLink to="/">Home</RouterLink>

<RouterLink to="/courses">Courses</RouterLink>

<RouterLink to="/profile">Profile</RouterLink>

</div>

<div>

Enrolled :
{{ store.enrolledCourses.length }}

</div>

</nav>

</template>

<script setup>

import { RouterLink } from "vue-router";

import { useEnrollmentStore } from "../stores/enrollment";

const store = useEnrollmentStore();

</script>
